# app/utils/json_parser.py
"""
Robust JSON Parser for LLM Responses
====================================
Handles common issues with JSON generated by LLMs:
- Markdown code blocks (```json ... ```)
- Trailing commas
- Unescaped quotes in strings
- Extra text before/after JSON
"""

import json
import re
from typing import Any, Optional, Union, List, Dict
from app.utils.logging import get_logger

logger = get_logger(__name__)


def extract_json_from_llm_response(
    response_text: str,
    expect_array: bool = False
) -> Optional[Union[Dict[str, Any], List[Any]]]:
    """
    Extract and parse JSON from an LLM response.
    
    Handles:
    - Markdown code blocks (```json ... ```)
    - Extra text before/after JSON
    - Common JSON syntax errors from LLMs
    
    Args:
        response_text: Raw text response from LLM
        expect_array: If True, expect a JSON array; if False, expect an object
        
    Returns:
        Parsed JSON as dict or list, or None if parsing fails
    """
    if not response_text:
        logger.warning("Empty response text received")
        return None
    
    text = response_text.strip()
    
    # Step 1: Remove markdown code blocks
    text = _strip_markdown_code_blocks(text)
    
    # Step 2: Try direct parsing first
    try:
        result = json.loads(text)
        return result
    except json.JSONDecodeError:
        pass
    
    # Step 3: Extract JSON using regex
    json_text = _extract_json_substring(text, expect_array)
    if json_text:
        try:
            result = json.loads(json_text)
            return result
        except json.JSONDecodeError:
            # Step 4: Try to repair common issues
            repaired = _repair_json(json_text)
            try:
                result = json.loads(repaired)
                logger.info("Successfully parsed JSON after repair")
                return result
            except json.JSONDecodeError as e:
                logger.warning(f"JSON repair failed: {e}")
    
    # Step 5: Last resort - try to repair the original text
    repaired = _repair_json(text)
    try:
        result = json.loads(repaired)
        logger.info("Successfully parsed JSON after full repair")
        return result
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse JSON after all attempts: {e}")
        logger.debug(f"Raw text (first 500 chars): {text[:500]}")
        return None


def _strip_markdown_code_blocks(text: str) -> str:
    """Remove markdown code block markers."""
    # Handle ```json ... ``` or ``` ... ```
    if text.startswith('```'):
        # Remove opening ``` with optional language specifier
        text = re.sub(r'^```(?:json|JSON)?\s*\n?', '', text)
        # Remove closing ```
        text = re.sub(r'\n?```\s*$', '', text)
    return text.strip()


def _extract_json_substring(text: str, expect_array: bool) -> Optional[str]:
    """Extract JSON object or array from text using bracket matching."""
    if expect_array:
        # Find first [ and match to closing ]
        start_char, end_char = '[', ']'
    else:
        # Try object first, then array
        if '{' in text:
            start_char, end_char = '{', '}'
        elif '[' in text:
            start_char, end_char = '[', ']'
        else:
            return None
    
    start_idx = text.find(start_char)
    if start_idx == -1:
        return None
    
    # Count brackets to find matching end
    depth = 0
    in_string = False
    escape_next = False
    
    for i, char in enumerate(text[start_idx:], start_idx):
        if escape_next:
            escape_next = False
            continue
            
        if char == '\\':
            escape_next = True
            continue
            
        if char == '"' and not escape_next:
            in_string = not in_string
            continue
            
        if in_string:
            continue
            
        if char == start_char:
            depth += 1
        elif char == end_char:
            depth -= 1
            if depth == 0:
                return text[start_idx:i + 1]
    
    # If we didn't find matching end, return from start to end
    return text[start_idx:]


def _repair_json(text: str) -> str:
    """
    Attempt to repair common JSON issues from LLMs.
    
    Fixes:
    - Trailing commas before } or ]
    - Single quotes instead of double quotes (outside of strings)
    - Unescaped newlines in strings
    - Missing quotes around keys
    """
    # Remove trailing commas before } or ]
    text = re.sub(r',\s*([}\]])', r'\1', text)
    
    # Fix unescaped newlines in strings (replace with \n)
    # This is tricky - we need to be inside a string
    lines = text.split('\n')
    repaired_lines = []
    in_string = False
    
    for i, line in enumerate(lines):
        if i > 0 and in_string:
            # We're continuing a string from the previous line
            repaired_lines[-1] = repaired_lines[-1] + '\\n' + line
        else:
            repaired_lines.append(line)
        
        # Count unescaped quotes to track string state
        quote_count = 0
        j = 0
        while j < len(line):
            if line[j] == '\\' and j + 1 < len(line):
                j += 2  # Skip escaped character
                continue
            if line[j] == '"':
                quote_count += 1
            j += 1
        
        # If odd number of quotes, string continues to next line
        if quote_count % 2 == 1:
            in_string = not in_string
    
    return '\n'.join(repaired_lines)


def parse_story_json(response_text: str) -> List[Dict[str, Any]]:
    """
    Parse story JSON from Gemini response.
    
    Args:
        response_text: Raw response from Gemini
        
    Returns:
        List of story page dictionaries
        
    Raises:
        ValueError: If JSON cannot be parsed
    """
    result = extract_json_from_llm_response(response_text, expect_array=True)
    
    if result is None:
        raise ValueError("Failed to parse story JSON from LLM response")
    
    if not isinstance(result, list):
        raise ValueError(f"Expected JSON array, got {type(result).__name__}")
    
    return result


def parse_analysis_json(response_text: str) -> Dict[str, Any]:
    """
    Parse analysis JSON from Gemini response.
    
    Args:
        response_text: Raw response from Gemini
        
    Returns:
        Analysis dictionary
        
    Raises:
        ValueError: If JSON cannot be parsed
    """
    result = extract_json_from_llm_response(response_text, expect_array=False)
    
    if result is None:
        raise ValueError("Failed to parse analysis JSON from LLM response")
    
    if not isinstance(result, dict):
        raise ValueError(f"Expected JSON object, got {type(result).__name__}")
    
    return result

